### ISSUE TITLE
improvements to csv/json results download

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-pdi#114]
A few items that come to mind:
- [x] when downloading a .csv, if there are multiple pages in the result, the name of the csv file should indicate the page clearly (having a `-page001` suffix for instance)
- [x] the query parameter `pageSize` should be documented on the query result page (maybe with a form asking the number of results per page)
- [ ] the number of results per page for a csv export should be higher so that it's easier for users who just want some results, maybe we can set it at 500 by default. This should be just a matter of adding the `pageSize` in the download csv link

**Comment by MarcAgate** [comment]
Done as of commit 2bbe04f. We now have the file names that end with _pXX.csv and it is possible to setup both the pageSize and the pageNumber after clicking on view/hide query, using the provided form.
However, the initial and default page size for csv is still 50 (this way you really download what's on the page; otherwise I find it could be confusing and inconsistent (WDYT ?)

**Comment by eroux** [comment]
I can't really test right now but I think it's good yes

**Comment by MarcAgate** [comment]
@eroux 
Can we close this one ?
