### ISSUE TITLE
api to download the whole ontology at once

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-pdi#134]
for the editor it would be important to have an endpoint where all the triples of the ontology are returned (in all serializations, with no reasoning), maybe this exists already? if not we should create it

**Comment by codam** [comment]
Nicolas is recommending that it would be good to have a versioning of the ontology, as modifications in the ontology could break the editor from working fine.

**Comment by eroux** [comment]
Do you mean serving all the versions of the ontology? That seems a bit difficult... I think from now on we can just be careful not to break things... the current changes to the data and ontology should be the last big ones

**Comment by MarcAgate** [comment]
We currently have http://purl.bdrc.io/ontology/admin.ttl or http://purl.bdrc.io/ontology/admin.EXT that I believe return all the triples of the ontology (due to the import mechanism).

**Comment by eroux** [comment]
Thanks, that should do! Raphael can you try?

**Comment by xristy** [comment]
It might be prudent to have a ontology version so that the editor could record what version it is intended to work with and if an internal error occurs then the current ontology version can be compared to the on the editor was _known_ to work with. It could help track down errors.

It is going to be necessary to be very circumspect about alterations like changing a property to be more restrictive which can invalidate many resources.

Perhaps we need an ontology validation task in ldspdi or editserv to validate the Fuseki dataset against the current ontology

**Comment by eroux** [comment]
Yes, I think an automatic CI test (there are some integrated in Github like TravisCI) running some tests of lds-pdi, blmp and pdl against a commit would be great, it's a bit of effort though, might not be top priority

**Comment by codam** [comment]
> Do you mean serving all the versions of the ontology? That seems a bit difficult... I think from now on we can just be careful not to break things... the current changes to the data and ontology should be the last big ones

Yes that is what Nicolas thought would be a good idea.
Maybe we could use the Github and its versioning system if we want to limit the effort in development?

> We currently have http://purl.bdrc.io/ontology/admin.ttl or http://purl.bdrc.io/ontology/admin.EXT that I believe returns all the triples of the ontology (due to the import mechanism).

I have a 404 error with http://purl.bdrc.io/ontology/admin.EXT
Would you have a xml version too?

By the way, in http://purl.bdrc.io/ontology/admin.ttl I see some imports. Ideally I would need a version where the imports are already done

> Thanks, that should do! Raphael can you try?

I tried with http://purl.bdrc.io/ontology/core.owl because it is in xml format, which is what the editor expects. (I am not 100% it is corresponding to the latest ontology version though).
I also know that it is not representing the full ontology, but a part of it.
There was the following errror message: "NamedNode IRI "core/AnyDate" must be absolute."
I suppose it is because of these types of nodes:   <rdfs:Datatype rdf:about="core/AnyDate">

**Comment by MarcAgate** [comment]
EXT must be either json, rdf, jsonld, nt, etc... these links are accessible on the home page http://purl.bdrc.io/ in the "ONTOLOGY SERVICE" section.

How do you get the "must be absolute" error message?

**Comment by codam** [comment]
> EXT must be either json, rdf, jsonld, nt, etc... these links are accessible on the home page http://purl.bdrc.io/ in the "ONTOLOGY SERVICE" section.

Got it!

> How do you get the "must be absolute" error message?

I tried again using http://purl.bdrc.io/ontology/admin.owl
This happens when the editor's parses this ontology file

**Comment by xristy** [comment]
regarding the errors when loading [admin.owl](http://purl.bdrc.io/ontology/admin.owl), see #135.
