### ISSUE TITLE
blank prefLabelMatch in rootSearchGraph

### ISSUE THREAD

**Issue by berger-n** [buda-base/lds-pdi#164]
see http://purl.bdrc.io/lib/rootSearchGraph?LG_NAME=fr&I_LIM=500&L_NAME=%22comparaison%20des%20versions%20chinoise%22

```
{ 
  xml:lang: "fr",
  type: "http://purl.bdrc.io/ontology/tmp/prefLabelMatch",
  value: ""
}
```

**Comment by berger-n** [comment]
same here: 
http://purl.bdrc.io/lib/rootSearchGraph?LG_NAME=en&I_LIM=500&L_NAME=%22university%22&format=json

**Comment by berger-n** [comment]
same here (with `altLabelMatch`):
http://purl.bdrc.io/lib/rootSearchGraph?LG_NAME=en&I_LIM=500&L_NAME=%22Noble%20Mah%C4%81y%C4%81na%20S%C5%ABtra%22&format=json

**Comment by eroux** [comment]
@xristy would you have time to take a look? this prevents a nice display of the English results (of 84000 for instance), it would be really cool to have a demo of that for next week if it's not too complex (if it's not there it's not a huge deal)

**Comment by eroux** [comment]
boils down to

```sparql
PREFIX text: <http://jena.apache.org/text#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

select ?TT ?sc ?lit1 where {
  (?TT ?sc ?lit1) text:query ( skos:prefLabel "\"university\""@en "highlight:" ).
}
```

**Comment by xristy** [comment]
I've narrowed the issue to [TextIndexLucene.java L676](https://github.com/buda-base/jena/blob/6c72fe76c0b6228a9a0100aa7aec80caf5b6b86f/jena-text/src/main/java/org/apache/jena/query/text/TextIndexLucene.java#L676).

The generated TokenStream is not correctly formed. The problem appears to be that the `effectiveField` is `label` instead of `label_en`.

**Comment by berger-n** [comment]
Great! 
Thanks
